import { describe, expect, it } from 'vitest';
import { AddressFields } from '../../components/address/AddressFields';
import { LoginContainer } from '../../components/auth/LoginContainer';
import { LoginForm } from '../../components/auth/LoginForm';
import { ClientLoginFormCard } from '../../components/auth/client/ClientLoginFormCard';
import { PlatformLoginForm } from '../../components/auth/platform/PlatformLoginForm';
import { PlatformLoginFormCard } from '../../components/auth/platform/PlatformLoginFormCard';
import { PlatformMfaForm } from '../../components/auth/platform/PlatformMfaForm';
import { PlatformMfaSetupForm } from '../../components/auth/platform/PlatformMfaSetupForm';
import { FilterDrawer } from '../../components/common/data/FilterDrawer';
import { SearchBar } from '../../components/common/data/SearchBar';
import { InfoList } from '../../components/common/display/InfoList';
import { KeyValueGrid } from '../../components/common/display/KeyValueGrid';
import { StatusChip } from '../../components/common/display/StatusChip';
import { AppSnackbar } from '../../components/common/feedback/AppSnackbar';
import { AppAutocomplete } from '../../components/common/form/AppAutocomplete';
import { AppForm } from '../../components/common/form/AppForm';
import { FormActions } from '../../components/common/form/FormActions';
import { FormTextField } from '../../components/common/form/FormTextField';
import { TotpCodeBoxes } from '../../components/common/form/TotpCodeBoxes';
import { CircularLoader } from '../../components/common/loading/CircularLoader';
import { SkeletonLoader } from '../../components/common/loading/SkeletonLoader';
import { BaseModal } from '../../components/common/modal/BaseModal';
import { StepperWizard } from '../../components/common/navigation/StepperWizard';
import { AppPopoverMenu } from '../../components/common/overlay/AppPopoverMenu';
import { AppTooltip } from '../../components/common/overlay/AppTooltip';
import { PageHeader } from '../../components/common/page/PageHeader';
import { SectionCard } from '../../components/common/page/SectionCard';
import { AvatarUploader } from '../../components/common/upload/AvatarUploader';
import { FileUpload } from '../../components/common/upload/FileUpload';
import { AppLayout } from '../../components/layout/admin-navigation/AppLayout';

describe('components smoke', () => {
  it('exports components not individually covered yet', () => {
    expect(AddressFields).toBeTruthy();
    expect(LoginContainer).toBeTruthy();
    expect(LoginForm).toBeTruthy();
    expect(ClientLoginFormCard).toBeTruthy();
    expect(PlatformLoginForm).toBeTruthy();
    expect(PlatformLoginFormCard).toBeTruthy();
    expect(PlatformMfaForm).toBeTruthy();
    expect(PlatformMfaSetupForm).toBeTruthy();
    expect(FilterDrawer).toBeTruthy();
    expect(SearchBar).toBeTruthy();
    expect(InfoList).toBeTruthy();
    expect(KeyValueGrid).toBeTruthy();
    expect(StatusChip).toBeTruthy();
    expect(AppSnackbar).toBeTruthy();
    expect(AppAutocomplete).toBeTruthy();
    expect(AppForm).toBeTruthy();
    expect(FormActions).toBeTruthy();
    expect(FormTextField).toBeTruthy();
    expect(TotpCodeBoxes).toBeTruthy();
    expect(CircularLoader).toBeTruthy();
    expect(SkeletonLoader).toBeTruthy();
    expect(BaseModal).toBeTruthy();
    expect(StepperWizard).toBeTruthy();
    expect(AppPopoverMenu).toBeTruthy();
    expect(AppTooltip).toBeTruthy();
    expect(PageHeader).toBeTruthy();
    expect(SectionCard).toBeTruthy();
    expect(AvatarUploader).toBeTruthy();
    expect(FileUpload).toBeTruthy();
    expect(AppLayout).toBeTruthy();
  });
});
