import { describe, expect, it } from 'vitest';
import { AddressFields } from '@shared/components/form/AddressFields';
import { LoginContainer } from '@features/platform/auth/components/LoginContainer';
import { LoginForm } from '@features/platform/auth/components/LoginForm';
import { ClientLoginFormCard } from '@features/client/auth/components/ClientLoginFormCard';
import { PlatformLoginForm } from '@features/platform/auth/components/PlatformLoginForm';
import { PlatformLoginFormCard } from '@features/platform/auth/components/PlatformLoginFormCard';
import { PlatformMfaForm } from '@features/platform/auth/components/PlatformMfaForm';
import { PlatformMfaSetupForm } from '@features/platform/auth/components/PlatformMfaSetupForm';
import { FilterDrawer } from '@shared/components/data-display/data/FilterDrawer';
import { SearchBar } from '@shared/components/data-display/data/SearchBar';
import { InfoList } from '@shared/components/data-display/InfoList';
import { KeyValueGrid } from '@shared/components/data-display/KeyValueGrid';
import { StatusChip } from '@shared/components/data-display/StatusChip';
import { AppSnackbar } from '@shared/components/feedback/AppSnackbar';
import { AppAutocomplete } from '@shared/components/form/AppAutocomplete';
import { AppForm } from '@shared/components/form/AppForm';
import { FormActions } from '@shared/components/form/FormActions';
import { FormTextField } from '@shared/components/form/FormTextField';
import { TotpCodeBoxes } from '@shared/components/form/TotpCodeBoxes';
import { AppCircularProgress } from '@shared/components/data-display/AppCircularProgress';
import { AppSkeleton } from '@shared/components/data-display/AppSkeleton';
import { BaseModal } from '@shared/components/modal/BaseModal';
import { StepperWizard } from '@shared/components/navigation/StepperWizard';
import { AppPopoverMenu } from '@shared/components/overlay/AppPopoverMenu';
import { AppTooltip } from '@shared/components/overlay/AppTooltip';
import { PageHeader } from '@shared/components/layout/PageHeader';
import { SectionCard } from '@shared/components/layout/SectionCard';
import { AvatarUploader } from '@shared/components/upload/AvatarUploader';
import { FileUpload } from '@shared/components/upload/FileUpload';
import { AppLayout } from '@app/layout/admin-navigation/AppLayout';

describe('components smoke', () => {
  it('exports components not individually covered yet', () => {
    expect(AddressFields).toBeTruthy();
    expect(LoginContainer).toBeTruthy();
    expect(LoginForm).toBeTruthy();
    expect(ClientLoginFormCard).toBeTruthy();
    expect(PlatformLoginForm).toBeTruthy();
    expect(PlatformLoginFormCard).toBeTruthy();
    expect(PlatformMfaForm).toBeTruthy();
    expect(PlatformMfaSetupForm).toBeTruthy();
    expect(FilterDrawer).toBeTruthy();
    expect(SearchBar).toBeTruthy();
    expect(InfoList).toBeTruthy();
    expect(KeyValueGrid).toBeTruthy();
    expect(StatusChip).toBeTruthy();
    expect(AppSnackbar).toBeTruthy();
    expect(AppAutocomplete).toBeTruthy();
    expect(AppForm).toBeTruthy();
    expect(FormActions).toBeTruthy();
    expect(FormTextField).toBeTruthy();
    expect(TotpCodeBoxes).toBeTruthy();
    expect(AppCircularProgress).toBeTruthy();
    expect(AppSkeleton).toBeTruthy();
    expect(BaseModal).toBeTruthy();
    expect(StepperWizard).toBeTruthy();
    expect(AppPopoverMenu).toBeTruthy();
    expect(AppTooltip).toBeTruthy();
    expect(PageHeader).toBeTruthy();
    expect(SectionCard).toBeTruthy();
    expect(AvatarUploader).toBeTruthy();
    expect(FileUpload).toBeTruthy();
    expect(AppLayout).toBeTruthy();
  });
});
