import {
  educationLevelService,
  gradeService,
  subjectService,
} from '@features/client/academic/services/service';

export const educationLevelCatalogConfig = {
  routeBase: '/client/education-levels',
  title: 'Níveis de ensino',
  subtitle: 'Organize os níveis usados por séries, turmas e matrículas.',
  detailsTitle: 'Detalhes do nível de ensino',
  detailsSubtitle: 'Consulte os dados do nível usado por séries, turmas e matrículas.',
  createTitle: 'Novo nível de ensino',
  createSubtitle: 'Cadastre a estrutura usada por séries, turmas e matrículas.',
  editTitle: 'Editar nível de ensino',
  editSubtitle: 'Atualize os dados estruturais usados por séries, turmas e matrículas.',
  emptyTitle: 'Nenhum nível de ensino encontrado',
  emptyDescription: 'Cadastre níveis de ensino para organizar séries e turmas.',
  toolbarDescription: 'Níveis de ensino alimentam séries, turmas e fluxos acadêmicos relacionados.',
  searchPlaceholder: 'Nome do nível de ensino',
  codePlaceholder: 'Código do nível de ensino',
  errorMessageFallback: 'Erro ao carregar níveis de ensino.',
  loadErrorMessage: 'Não foi possível carregar o nível de ensino.',
  submitErrorMessage: 'Não foi possível salvar o nível de ensino.',
  createPermission: 'education-level:create',
  service: educationLevelService,
  showEducationLevel: false,
};

export const gradeCatalogConfig = {
  routeBase: '/client/grades',
  title: 'Séries',
  subtitle: 'Gerencie séries e anos escolares por nível de ensino.',
  detailsTitle: 'Detalhes da série',
  detailsSubtitle: 'Consulte os dados da série e o nível de ensino vinculado.',
  createTitle: 'Nova série',
  createSubtitle: 'Cadastre séries e anos escolares vinculados aos níveis de ensino.',
  editTitle: 'Editar série',
  editSubtitle: 'Atualize série, código, status e o nível de ensino vinculado.',
  emptyTitle: 'Nenhuma série encontrada',
  emptyDescription: 'Cadastre séries para organizar turmas e matrículas.',
  toolbarDescription: 'Séries podem ser vinculadas a níveis de ensino, turmas e matrículas.',
  searchPlaceholder: 'Nome da série',
  codePlaceholder: 'Código da série',
  errorMessageFallback: 'Erro ao carregar séries.',
  loadErrorMessage: 'Não foi possível carregar a série.',
  submitErrorMessage: 'Não foi possível salvar a série.',
  createPermission: 'grade:create',
  service: gradeService,
  showEducationLevel: true,
};

export const subjectCatalogConfig = {
  routeBase: '/client/subjects',
  title: 'Disciplinas',
  subtitle: 'Gerencie disciplinas usadas nas turmas e boletins.',
  detailsTitle: 'Detalhes da disciplina',
  detailsSubtitle: 'Consulte os dados da disciplina usada em turmas e boletins.',
  createTitle: 'Nova disciplina',
  createSubtitle: 'Cadastre disciplinas usadas em turmas, frequência e boletins.',
  editTitle: 'Editar disciplina',
  editSubtitle: 'Atualize nome, código, status e descrição da disciplina.',
  emptyTitle: 'Nenhuma disciplina encontrada',
  emptyDescription: 'Cadastre disciplinas para compor turmas e boletins.',
  toolbarDescription:
    'Disciplinas são reutilizadas em vínculos docentes, turmas, frequência e boletins.',
  searchPlaceholder: 'Nome da disciplina',
  codePlaceholder: 'Código da disciplina',
  errorMessageFallback: 'Erro ao carregar disciplinas.',
  loadErrorMessage: 'Não foi possível carregar a disciplina.',
  submitErrorMessage: 'Não foi possível salvar a disciplina.',
  createPermission: 'subject:create',
  service: subjectService,
  showEducationLevel: false,
};
